
default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  pool: <%= ENV["DB_POOL"] || 5 %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  port: <%= ENV['PG_PORT'] || 5432 %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['PG_DEV_DATABASE'] || 'ds_soundcloud_dev' %>

test:
  <<: *default
  database: <%= ENV['PG_TEST_DATABASE'] || 'ds_soundcloud_test' %>

production:
  <<: *default

